### ISSUE TITLE
Database with a Float64 column.

### ISSUE THREAD

**Issue by alvaro1101** [JuliaDB/SQLite.jl#119]
I can query all columns of the database except one with the type `Float64`
```
ERROR: LoadError: InexactError()
 in Nullable{Int64}(::Float64) at ./sysimg.jl:53
 in streamfrom(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::Type{Nullable{Int64}}, ::Int64, ::Int64) at /home/am/.julia/v0.5/SQLite/src/Source.jl:89
 in streamto!(::DataFrames.DataFrame, ::Type{DataStreams.Data.Field}, ::SQLite.Source, ::Type{Nullable{Int64}}, ::Type{Nullable{Int64}}, ::Int64, ::Int64, ::DataStreams.Data.Schema{false}, ::Base.#identity) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:171
 in stream!(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::DataFrames.DataFrame, ::DataStreams.Data.Schema{false}, ::DataStreams.Data.Schema{false}, ::Array{Function,1}) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:202
 in #stream!#5(::Array{Any,1}, ::Function, ::SQLite.Source, ::Type{DataFrames.DataFrame}, ::Bool, ::Dict{Int64,Function}) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:149
 in #query#16 at /home/am/.julia/v0.5/SQLite/src/Source.jl:125 [inlined]
 in query(::SQLite.DB, ::String, ::Type{DataFrames.DataFrame}) at /home/am/.julia/v0.5/SQLite/src/Source.jl:124
 in query(::SQLite.DB, ::String) at /home/am/.julia/v0.5/SQLite/src/Source.jl:117
 in include_from_node1(::String) at ./loading.jl:488
...
```

**Comment by quinnj** [comment]
The issue here is that the table you're trying to read from isn't consistent on types. I.e. it's trying to read an `Int64`, but it's getting a `Float64`. One thing you can do is `SQLite.query(db, sql; stricttypes=false)` and it will return no matter what types of values are actually stored. I've also improved this "type detection" on master, so if you do `Pkg.checkout("SQLite")`, then restart julia, it may solve your problem (it depends on if the column in question is actually stored in the table, which I would assume is the case).

Which reminds me, I need to get a new tag out for this package, I'll try to do that pretty soon.

**Comment by alvaro1101** [comment]
Thanks... The use of `stricttypes=false` make the thing works.

I'm already in master.

Yes, the column is in the table.
