### ISSUE TITLE
some missing functionality from earlier versions

### ISSUE THREAD

**Issue by Ph0non** [JuliaDB/SQLite.jl#60]
After a while I'm using julia again and update all the packages, so also SQLite. In need to run an earlier project I try to retain the most code. But with the new version of SQLite I have some problems, that seems to be a step back for me.

It was a very comprehensible way to use symbols in results of a query to address specific columns like `sample[:sample_date]` instead of `sample[3]`.
Further I get errors from commands like 
```
julia> sample[:]
ERROR: 'endof' has no method matching endof(::SQLite.ResultSet)

julia> sample[:, 2:end]
ERROR: 'ndims' has no method matching ndims(::SQLite.ResultSet)
 in trailingsize at abstractarray.jl:58
```

Are there other ways to retain a comprehensible way from earlier versions and a solution for `:` and `end` or at least a way to downgrade SQLite to an earlier version?

Something like `sample[ find(sample.colnames .== "sample_date")[1] ]` works, but is unnecessary bloated.

**Comment by Sean1708** [comment]
@quinnj replaced the DataFrames requirement with a more lightweight solution (our `ResultSet`). I remember him saying that it is quite simple to turn a `ResultSet` into a `DataFrame` but I can't for the life of me remember how. If I get some time I'll have a play around tonight and see if I can figure it out, unfortunately I'm in the middle of exams so I can't dedicate too much time to it.

If you do figure it out before tonight, let me know so that I can put it in the README.

**Comment by Sean1708** [comment]
@Ph0non To do this first make sure `DataFrames` is installed then do the following (assuming you've already set up your database).

```julia
...

julia> using DataFrames

julia> rs = query(db, "SELECT...
...

julia> df = DataFrame(rs.values, convert(Vector{Symbol}, rs.colnames))
...
```

@quinnj It would be nice to make `ResultSet` play a bit more nicely with `DataFrame` either by making `ResultSet` a bit more `DataFrame`y or by storing the column names as symbols so that the above example is a bit simpler. What do you think?

**Comment by quinnj** [comment]
Hmmm...this is a good question, another use case of conditional modules that has been talked about in Base (if and when DataFrames was loaded, we could run some SQLite + DataFrames glue code). I think I have another version of your solution that actually uses a smarter `strings_to_symbols` function they've put together in DataFrames. I'll try to find it tonight and post.

**Comment by quinnj** [comment]
We now return `Data.Table` from SQLite queries and as long as you've done `using DataFrames` before `using SQLite`, then you'll get the `DataFrame(dt::Data.Table)` conversion method as well. i.e. you can efficiently convert a `Data.Table` to a `DataFrame` with that function call (non-copying).
