### ISSUE TITLE
compile-time settings

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaDB/SQLite.jl#67]
suggestions on settings/defines when compiling SQLITE for multidisciplinary use

Compiling in extensions.c math and string funcs would be helpful:
< www.sqlite.org/contrib/download/extension-functions.c?get=25 >
```C
SQLITE_DEFAULT_FOREIGN_KEYS=1        enforce explicit foreign keys
SQLITE_SECURE_DELETE=1               overwrite deleted data with zeros
SQLITE_ALLOW_COVERING_INDEX_SCAN=1   improve performance
SQLITE_ENABLE_API_ARMOR=1            trap some bad behavior
SQLITE_ENABLE_COLUMN_METADATA=1      db, table, col src of SELECTed col
SQLITE_ENABLE_FTS3=1                 full text search engine (FTS3 & FTS4)
SQLITE_ENABLE_FTS3_PARENTHESIS=1     AND, NOT ops for full text search

SQLITE_ENABLE_RTREE=1?               enable 2D boxed range databases
                                     very powerful when needed, adds size

SQLITE_THREADSAFE=?
    I have no experience with this, nonetheless 0 or 1 (not 2)
    Given julia's mindmeld with mulipilicity (muti-thread,core,server..)
    it is not clear that =0 (single threaded) allows clean multiagent use.
    It is clear that =0 runs faster as there is no locking overhead and
    no need for interfacing code to check for and handle responses
    of SQLITE_BUSY and SQLITE_LOCKED.

no SQLITE_DISABLE_ options and no SQLITE_OMIT_ options
```

**Comment by Sean1708** [comment]
BinDeps tends to prefer a system installation of SQLite (on OSX for example it uses `/usr/lib/libsqlite3.dylib`) so I'm a little worried that might lead to an inconsistent user experience. I'll let @quinnj weigh-in on that however, since he knows more about it than I do.

Regarding `extensions.c`, however, I think most of these are implemented in Julia already so it might be easier (for the time being anyway) to load them in as and when you need them using the [UDF API](https://github.com/quinnj/SQLite.jl#custom-scalar-functions).

**Comment by JeffreySarnoff** [comment]
UDF API, I agree that's good enough to cover common uses for extensions.c .. thanks.

Most of the time, apps and systems deliver a less than fully capable SQLite.

Blissfully unaware of BinDep workings, offering more of what SQLite does well would better serve the great variety of work users of julia bring. it hurts to consider predicating julia's goto database service and on-call table datastore on a capability restricted SQLite.

**Comment by quinnj** [comment]
I'm not sure there's anything we need to do here; a custom SQLite lib file can be provided, compiled however you'd like.
